// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://isdxnskghygvaezqjbyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzZHhuc2tnaHlndmFlenFqYnl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1MjI4NDUsImV4cCI6MjA4NzA5ODg0NX0.DINKyHd59TnlOmSeCa6A0INj4BtTASMv3--xsXebqco";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables. Please check your .env file.'
  );
}

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
