// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://noqfwivaapecxbvoghuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vcWZ3aXZhYXBlY3hidm9naHVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2MDAxNzUsImV4cCI6MjA4NzE3NjE3NX0.WuQR7uGmK1UklClXsFYaU34ndsS4jRw1K9FYbDj8BQU";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables. Please check your .env file.'
  );
}

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
